//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEleccionesWS.MilitanteWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Militante", Namespace="http://schemas.datacontract.org/2004/07/EleccionesWS.Domain")]
    [System.SerializableAttribute()]
    public partial class Militante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMilitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDocIdentidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCargo {
            get {
                return this.IdCargoField;
            }
            set {
                if ((this.IdCargoField.Equals(value) != true)) {
                    this.IdCargoField = value;
                    this.RaisePropertyChanged("IdCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMilitante {
            get {
                return this.IdMilitanteField;
            }
            set {
                if ((this.IdMilitanteField.Equals(value) != true)) {
                    this.IdMilitanteField = value;
                    this.RaisePropertyChanged("IdMilitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDocIdentidad {
            get {
                return this.NroDocIdentidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDocIdentidadField, value) != true)) {
                    this.NroDocIdentidadField = value;
                    this.RaisePropertyChanged("NroDocIdentidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltroListarMilitante", Namespace="http://schemas.datacontract.org/2004/07/EleccionesWS.Domain")]
    [System.SerializableAttribute()]
    public partial class FiltroListarMilitante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCargoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCargo {
            get {
                return this.IdCargoField;
            }
            set {
                if ((this.IdCargoField.Equals(value) != true)) {
                    this.IdCargoField = value;
                    this.RaisePropertyChanged("IdCargo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MilitanteWs.IMilitanteService")]
    public interface IMilitanteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilitanteService/BuscarMilitante", ReplyAction="http://tempuri.org/IMilitanteService/BuscarMilitanteResponse")]
        TestEleccionesWS.MilitanteWs.Militante BuscarMilitante(System.Nullable<int> idMilitante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilitanteService/BuscarMilitante", ReplyAction="http://tempuri.org/IMilitanteService/BuscarMilitanteResponse")]
        System.Threading.Tasks.Task<TestEleccionesWS.MilitanteWs.Militante> BuscarMilitanteAsync(System.Nullable<int> idMilitante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilitanteService/ListarMilitantes", ReplyAction="http://tempuri.org/IMilitanteService/ListarMilitantesResponse")]
        TestEleccionesWS.MilitanteWs.Militante[] ListarMilitantes(TestEleccionesWS.MilitanteWs.FiltroListarMilitante filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilitanteService/ListarMilitantes", ReplyAction="http://tempuri.org/IMilitanteService/ListarMilitantesResponse")]
        System.Threading.Tasks.Task<TestEleccionesWS.MilitanteWs.Militante[]> ListarMilitantesAsync(TestEleccionesWS.MilitanteWs.FiltroListarMilitante filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilitanteService/MilitanteAsignadoAOed", ReplyAction="http://tempuri.org/IMilitanteService/MilitanteAsignadoAOedResponse")]
        bool MilitanteAsignadoAOed(System.Nullable<int> idMilitante, System.Nullable<int> idOed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMilitanteService/MilitanteAsignadoAOed", ReplyAction="http://tempuri.org/IMilitanteService/MilitanteAsignadoAOedResponse")]
        System.Threading.Tasks.Task<bool> MilitanteAsignadoAOedAsync(System.Nullable<int> idMilitante, System.Nullable<int> idOed);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMilitanteServiceChannel : TestEleccionesWS.MilitanteWs.IMilitanteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MilitanteServiceClient : System.ServiceModel.ClientBase<TestEleccionesWS.MilitanteWs.IMilitanteService>, TestEleccionesWS.MilitanteWs.IMilitanteService {
        
        public MilitanteServiceClient() {
        }
        
        public MilitanteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MilitanteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MilitanteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MilitanteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestEleccionesWS.MilitanteWs.Militante BuscarMilitante(System.Nullable<int> idMilitante) {
            return base.Channel.BuscarMilitante(idMilitante);
        }
        
        public System.Threading.Tasks.Task<TestEleccionesWS.MilitanteWs.Militante> BuscarMilitanteAsync(System.Nullable<int> idMilitante) {
            return base.Channel.BuscarMilitanteAsync(idMilitante);
        }
        
        public TestEleccionesWS.MilitanteWs.Militante[] ListarMilitantes(TestEleccionesWS.MilitanteWs.FiltroListarMilitante filtro) {
            return base.Channel.ListarMilitantes(filtro);
        }
        
        public System.Threading.Tasks.Task<TestEleccionesWS.MilitanteWs.Militante[]> ListarMilitantesAsync(TestEleccionesWS.MilitanteWs.FiltroListarMilitante filtro) {
            return base.Channel.ListarMilitantesAsync(filtro);
        }
        
        public bool MilitanteAsignadoAOed(System.Nullable<int> idMilitante, System.Nullable<int> idOed) {
            return base.Channel.MilitanteAsignadoAOed(idMilitante, idOed);
        }
        
        public System.Threading.Tasks.Task<bool> MilitanteAsignadoAOedAsync(System.Nullable<int> idMilitante, System.Nullable<int> idOed) {
            return base.Channel.MilitanteAsignadoAOedAsync(idMilitante, idOed);
        }
    }
}
