//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEleccionesWS.MesaWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mesa", Namespace="http://schemas.datacontract.org/2004/07/EleccionesWS.Domain")]
    [System.SerializableAttribute()]
    public partial class Mesa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCentroVotacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdMesaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdOedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCentroVotacion {
            get {
                return this.IdCentroVotacionField;
            }
            set {
                if ((this.IdCentroVotacionField.Equals(value) != true)) {
                    this.IdCentroVotacionField = value;
                    this.RaisePropertyChanged("IdCentroVotacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdMesa {
            get {
                return this.IdMesaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMesaField, value) != true)) {
                    this.IdMesaField = value;
                    this.RaisePropertyChanged("IdMesa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdOed {
            get {
                return this.IdOedField;
            }
            set {
                if ((this.IdOedField.Equals(value) != true)) {
                    this.IdOedField = value;
                    this.RaisePropertyChanged("IdOed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MesaWs.IMesaService")]
    public interface IMesaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaService/BuscarMesa", ReplyAction="http://tempuri.org/IMesaService/BuscarMesaResponse")]
        TestEleccionesWS.MesaWs.Mesa BuscarMesa(string idMesa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMesaService/BuscarMesa", ReplyAction="http://tempuri.org/IMesaService/BuscarMesaResponse")]
        System.Threading.Tasks.Task<TestEleccionesWS.MesaWs.Mesa> BuscarMesaAsync(string idMesa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMesaServiceChannel : TestEleccionesWS.MesaWs.IMesaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaServiceClient : System.ServiceModel.ClientBase<TestEleccionesWS.MesaWs.IMesaService>, TestEleccionesWS.MesaWs.IMesaService {
        
        public MesaServiceClient() {
        }
        
        public MesaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MesaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestEleccionesWS.MesaWs.Mesa BuscarMesa(string idMesa) {
            return base.Channel.BuscarMesa(idMesa);
        }
        
        public System.Threading.Tasks.Task<TestEleccionesWS.MesaWs.Mesa> BuscarMesaAsync(string idMesa) {
            return base.Channel.BuscarMesaAsync(idMesa);
        }
    }
}
