using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Runtime.Serialization;
namespace TestEleccionesWS
{
     
    public class Constantes
    {

        public const string ERROR_FILTRO_LISTAR_MILITANTE_REQUERIDO = "FILTRO_LISTAR_MILITANTE_REQUERIDO";
        public const string ERROR_MILITANTE_NO_HALLADO = "MILITANTE_NO_HALLADO"; 
        
        public const string ERROR_MESA_NO_HALLADA = "MESA_NO_HALLADA";

        public const string ERROR_ARCHIVO_ACTA_REQUERIDO = "ARCHIVO_ACTA_REQUERIDO";

        public const string ERROR_MILITANTE_REGISTRO_ACTA_NO_HALLADO = "MILITANTE_REGISTRO_ACTA_NO_HALLADO";
        public const string ERROR_REGISTRO_ACTA_CARGO_INVALIDO = "MILITANTE_REGISTRO_ACTA_CARGO_INVALIDO";

        public const string ERROR_MILITANTE_REGISTRO_ACTA_NO_ASIGNADO_OED = "MILITANTE_REGISTRO_ACTA_NO_ASIGNADO_OED";

        public const string ERROR_NOMBRE_ARCHIVO_ACTA_LONGITUD_INVALIDA = "NOMBRE_ARCHIVO_ACTA_LONGITUD_INVALIDA";


        public const string ERROR_ID_MESA_REQUERIDO = "ID_MESA_REQUERIDO";
        public const string ERROR_ID_MILITANTE_PRESIDENTE_REQUERIDO = "ID_MILITANTE_PRESIDENTE_REQUERIDO";

        public const string ERROR_ID_MILITANTE_SECRETARIO_REQUERIDO = "ID_MILITANTE_SECRETARIO_REQUERIDO";

        public const string ERROR_ID_MILITANTE_TERCER_MIEMBRO_REQUERIDO = "ID_MILITANTE_TERCER_MIEMBRO_REQUERIDO";
        public const string ERROR_ID_MILITANTE_REGISTRO_REQUERIDO = "ID_MILITANTE_REGISTRO_REQUERIDO";
        public const string ERROR_OBSERVACIONES_ACTA_EXCEDE_1000_CARACTERES = "OBSERVACIONES_ACTA_EXCEDE_1000_CARACTERES";
        public const string ERROR_NO_ES_POSIBLE_ASIGNAR_FECHA_REGISTRO_ACTA = "NO_ES_POSIBLE_ASIGNAR_FECHA_REGISTRO_ACTA";
        public const string ERROR_NO_ES_POSIBLE_ASIGNAR_ESTADO_ACTA = "NO_ES_POSIBLE_ASIGNAR_ESTADO_ACTA";
        public const string ERROR_DETALLES_ACTA_REQUERIDOS = "DETALLES_ACTA_REQUERIDOS";
        public const string ERROR_ID_MILITANTE_CANDIDATO_EN_DETALLE_ACTA_REQUERIDO = "ID_MILITANTE_CANDIDATO_EN_DETALLE_ACTA_REQUERIDO";
        public const string ERROR_CANT_VOTOS_EN_DETALLE_ACTA_REQUERIDO = "CANT_VOTOS_EN_DETALLE_ACTA_REQUERIDO";

        public const string ERROR_CANT_VOTOS_EN_DETALLE_DEBE_MAYOR_0 = "CANT_VOTOS_EN_DETALLE_DEBE_MAYOR_0";

        
    }
}