//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEleccionesWS.Elecciones2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Acta", Namespace="http://schemas.datacontract.org/2004/07/EleccionesWS")]
    [System.SerializableAttribute()]
    public partial class Acta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TestEleccionesWS.Elecciones2.DetalleActa[] DetallesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdMesaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMilitantePresidenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMilitanteRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMilitanteSecretarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMilitanteTercerMiembroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TestEleccionesWS.Elecciones2.DetalleActa[] Detalles {
            get {
                return this.DetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesField, value) != true)) {
                    this.DetallesField = value;
                    this.RaisePropertyChanged("Detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRegistroField, value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdMesa {
            get {
                return this.IdMesaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMesaField, value) != true)) {
                    this.IdMesaField = value;
                    this.RaisePropertyChanged("IdMesa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMilitantePresidente {
            get {
                return this.IdMilitantePresidenteField;
            }
            set {
                if ((this.IdMilitantePresidenteField.Equals(value) != true)) {
                    this.IdMilitantePresidenteField = value;
                    this.RaisePropertyChanged("IdMilitantePresidente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMilitanteRegistro {
            get {
                return this.IdMilitanteRegistroField;
            }
            set {
                if ((this.IdMilitanteRegistroField.Equals(value) != true)) {
                    this.IdMilitanteRegistroField = value;
                    this.RaisePropertyChanged("IdMilitanteRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMilitanteSecretario {
            get {
                return this.IdMilitanteSecretarioField;
            }
            set {
                if ((this.IdMilitanteSecretarioField.Equals(value) != true)) {
                    this.IdMilitanteSecretarioField = value;
                    this.RaisePropertyChanged("IdMilitanteSecretario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMilitanteTercerMiembro {
            get {
                return this.IdMilitanteTercerMiembroField;
            }
            set {
                if ((this.IdMilitanteTercerMiembroField.Equals(value) != true)) {
                    this.IdMilitanteTercerMiembroField = value;
                    this.RaisePropertyChanged("IdMilitanteTercerMiembro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreArchivo {
            get {
                return this.NombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreArchivoField, value) != true)) {
                    this.NombreArchivoField = value;
                    this.RaisePropertyChanged("NombreArchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleActa", Namespace="http://schemas.datacontract.org/2004/07/EleccionesWS")]
    [System.SerializableAttribute()]
    public partial class DetalleActa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantVotosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdMesaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdMilitanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CantVotos {
            get {
                return this.CantVotosField;
            }
            set {
                if ((this.CantVotosField.Equals(value) != true)) {
                    this.CantVotosField = value;
                    this.RaisePropertyChanged("CantVotos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdMesa {
            get {
                return this.IdMesaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMesaField, value) != true)) {
                    this.IdMesaField = value;
                    this.RaisePropertyChanged("IdMesa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdMilitante {
            get {
                return this.IdMilitanteField;
            }
            set {
                if ((this.IdMilitanteField.Equals(value) != true)) {
                    this.IdMilitanteField = value;
                    this.RaisePropertyChanged("IdMilitante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Elecciones2.IActaService")]
    public interface IActaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActaService/RegistrarActa", ReplyAction="http://tempuri.org/IActaService/RegistrarActaResponse")]
        void RegistrarActa(TestEleccionesWS.Elecciones2.Acta acta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActaService/RegistrarActa", ReplyAction="http://tempuri.org/IActaService/RegistrarActaResponse")]
        System.Threading.Tasks.Task RegistrarActaAsync(TestEleccionesWS.Elecciones2.Acta acta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActaServiceChannel : TestEleccionesWS.Elecciones2.IActaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActaServiceClient : System.ServiceModel.ClientBase<TestEleccionesWS.Elecciones2.IActaService>, TestEleccionesWS.Elecciones2.IActaService {
        
        public ActaServiceClient() {
        }
        
        public ActaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistrarActa(TestEleccionesWS.Elecciones2.Acta acta) {
            base.Channel.RegistrarActa(acta);
        }
        
        public System.Threading.Tasks.Task RegistrarActaAsync(TestEleccionesWS.Elecciones2.Acta acta) {
            return base.Channel.RegistrarActaAsync(acta);
        }
    }
}
